apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:QKpjn9Qd224a7EN7D3PrsflfkB/wno2zdH5PCjll1bfC7cTfN/O/xg==,iv:PreJaq2wL+9EkzF2Z9Dgiy4Z8Df9f9CnCEWGBma+iHM=,tag:nthTiKvhuYz/9BTHZu6MWQ==,type:str]
sops:
  age:
    - recipient: age1658d87m9qz4fmvlqprxjr4xen79hule9pww4y54ah0kr75lw9suswy0ux7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRnZIUFBseGlRV2xPQjR4
        amxyaDQ1WlJVWWVHUTlINWNpWjRXU2pReUZNClBkM0VVQWRKeWtSbTh1WW0yVDVm
        OXQ5UVBQcSt5L2hDU0hEODhQVkdGcE0KLS0tIDNYUGtrNVB5cFhjaWtOZURGR3B1
        TzRRZTRVWGJsMnV6ZEV3RWxWM09rVkEK8sXEhjezYdNXY0ORc9Fhh4/AgOOFyUMC
        uffjM9lw/iYDOODz6qXAKDXOun8LXXPqylSlWegfk2+krKqm5hrktw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T00:11:07Z"
  mac: ENC[AES256_GCM,data:f+i8HdRj10rBhuPPVX0OpKfezjdkLTXpPBknRXaPl/Y3C6fxBPXcBOcPVq2qdniIVDCPX1TrZlHWjlhroLQqANIvwWLkSq8e8csRDZI2jXNw63Z8LKZgsezMzBfk8TNuwJ/LxeCqkG/mGABIiscVxWQkL7YG1FmJQSy87OwQ8QM=,iv:gvoV8ExRfY6XlTIryeicGwvZb5aQPB/t5FhNev0z+L4=,tag:+wOMLjxPO/FmiCHKFKl6Dw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
