apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:u7pL/vdO9y8k,iv:temn48W/JjijbLGVDaiWBm+GZEKAGHfnBzExC45ZI+0=,tag:b6C6646+xTle79D9WAZH9w==,type:str]
sops:
  age:
    - recipient: age1658d87m9qz4fmvlqprxjr4xen79hule9pww4y54ah0kr75lw9suswy0ux7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0K2drSUEzdm5xZktZWmtN
        ZlVSNDlNZWRqSWxSZitLUGlYOXdpMUQ2QjBVCnJRZmJpS1hOaHA4dmJ5b2xwdFBX
        MEdIWE1SWHNZcExqZTN6dDNDRnFGT0EKLS0tIElRMU1wVlV6UEhNeFA0NVBQWWxP
        TVJNbEIySVpsamMxZjNPVFNVeWdJZGMKrs47TlZ7Lswgtm2oicTuwZI9xiDzEfP+
        AXAYtW6pnxLi213nl9x0BJQG0g0iCCpHmKfMg7dTWrsSIX44g3EvuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T00:11:07Z"
  mac: ENC[AES256_GCM,data:GiMCMYoalDvUNX0bFWTI+Vc1oBSmjuA/WVuUcOaAkGDFlEkJPSKi0bKdwEuR+cki3fhnTNvJFIsdWpHKRLbbklReXXv8wfqrBVIX7wrTzGb5OWsQ7qidATts5JnN5iXTThBvVuOSIELHtIIuoR0QRSjyuVqEyL8Vvm0ozlhSvd8=,iv:RssgtynQo/pe38qpVsARY2l+PaeD1BKsI01cuFvWL6Q=,tag:iXz3Ss6OrDkgyw8j6mrYOg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
