apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:YecoA8UNGhP5Do5AApBnlQeXJSSWMVnW7uXX6SUFYxY=,iv:c/7ARAPwZYPWoHUPVrs1rc5XHf1asIFPvVbI4xLs/ME=,tag:xo6/czgEoYnVSdMbXUZeMA==,type:str]
sops:
  age:
    - recipient: age1658d87m9qz4fmvlqprxjr4xen79hule9pww4y54ah0kr75lw9suswy0ux7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVkp1VXJPSm1aZGVOalhI
        VlhWelhJOEdaRVdLR3hUWm5CYjlHWGlFQXlvCmpVSzVHbjdYbUVJZVVPZkNPUFJO
        cGtVa2trY2M3b2tlMytoWEhtRlY3OTAKLS0tIFJJM1Nzb0VoSUs1c3diRkhYeWNM
        MlRjeExreWFadFZLTlR5ejJ2ZC8rUVkKtGzqLijCRFpL9956lkUD5B/jPhm7CbFU
        nJnk+IM0QdFPatsQkhXjKU98oxsVtAKgRGddrwv3dfz3BLTs/vyl+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T00:11:07Z"
  mac: ENC[AES256_GCM,data:GEi8TNUs49UYDi1f6H1Nq71AG8YoKAfJRaK8l54A53Nv54f5DRM72mG+sqwuxGBFkGXtFL+WjeFxWwCujIk2GKuxMt4TXEPGxvL0xd5rC69irVWIOpdSHURWKYoTfEx3xJBcLJzgq8FIwo9F99KSGRttSuYtEid8cL4dWGF0SJU=,iv:bX/3Fedj/G4gf82Bl8jpAB9+YJ5qlBBWnxLD4g+feQs=,tag:JbNubkm6YvHEOzfVvWcmaQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
