apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:k30c71gyYSw+XSk2Oa+wwUdaY1TMF5mO2uF5pI3al7J0btnNWu/isT8JLKP/rCPEATXBTsOr1njTJdcv4LcuqXTqwLmjo09gxv9HQ8BbpdbgCM6/ak3KbbqXIxPq/hqnghUlL+gMA3Lgas8WnMtqRB9Uz/hHUJRQAMncnq7SGYnvYjo7W5YHn7VBXRi4LHeUfkKCsziebZRbP7SGt/Cj0GorZykuSGZ95wyZsQMCzJ6qrD+O,iv:XwukUJQanRUc4137vocmBWjjojm0e5SQ1rIhxdmydaY=,tag:13NZYsRbeq49LbZGYk4+xw==,type:str]
sops:
  age:
    - recipient: age1658d87m9qz4fmvlqprxjr4xen79hule9pww4y54ah0kr75lw9suswy0ux7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdTdZdDZZdHVQOCtYc1Iw
        bzRTUWJzNDh4WGswS05reDJ5TkdyZ1NOaWg4CkJ5SDZKbFFpcHE4ZUZ0dzhPd1hP
        bGNDOUtiTGNvdjFIbG91ZmJNU3RpVjAKLS0tIEFsMXFCTDZDOHVYcWhUUEtGSFJi
        ZHZrWjg0REFlRktpQWVBam9JdnI5RWcK3OThtevp17AJba9dwEQ96yePNWBabQ/X
        kNrAF87BoP5aRC0nAwzV/urohc8HvVnYajVj3Zu0wdW4Ff/WKkWlBQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T00:11:07Z"
  mac: ENC[AES256_GCM,data:/oYNv4w/saoQAMTQsq2QWAyRBM6EsDmt5sGol1DM/vCDoGRFJY7g+6PIg6AQvINnqpDvuuCt5tQw5honcM0y2f95RKmcO3DFhcrtp3VqsmceG0wkvk0dS+fEpnWf+HYfLW9s6w7JDrEwBZOR2yWKPiGcOf4sc98c2o1JyxJ5DS4=,iv:IjwgNS78lHU49P6FspokkAI64+bt+FGkrVGvc6BdcR4=,tag:TSxmMMzzJNuKqrjCEqM+Sg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
