apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:cT+qQYaw8Ug7XTt+ENbhrj2CvxI6KjkDagOBkPjduwRXHRcEadY4Lw==,iv:1HpmdJpkpIVCeyD0z9BiP4WOb5bdF/eSZBLJ9PWV84Y=,tag:1DqG6MJkF2YzXAwANTwYtA==,type:str]
sops:
  age:
    - recipient: age1658d87m9qz4fmvlqprxjr4xen79hule9pww4y54ah0kr75lw9suswy0ux7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZUN5R1BOVjhlc3RCc2Fl
        R2xOTFNFRG5RbE5lOENQZnRjYlRoT1hWN1RFCkVZR0dMa05IMlhYSzVxK3hYL0Rv
        Q05mRnp2ck5jRWpjYm1yNWU0V0t6eDgKLS0tIFlTQ3VoWnNGcVcyZXI0Ni9qdCt0
        TzBaMC9IaS9qa0loRE54RGFhcUdmWm8KFQxPjMVNmZxtLcyXx3Q6TzQwpeb2Dl10
        BVHWzVSY3j5vdkcAjSS0k7xO6+4V5M+ig/aION8ydVNXPDb0/3cBnQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T00:11:07Z"
  mac: ENC[AES256_GCM,data:W9VXljs48Cq30+pRhEDvELF4YVd8/b6SdVTChiZCV0l5RwvE+kEnt6NRCpBeIStviH4nXBJYPAQ2qgF0L3rFzZFkkfuj/YtsEvhN3zKUkXlhawZeFI+SOxBpkbWAQ++H/Ao86/wsml+9lhCOf3gW7wU/i64B/V+2ORKWCwYVY70=,iv:VqI+YfMb0sEp3ho9bCNRT7kK+X10UFBTb+xm1PyGD/4=,tag:Nzs3eLWYDFvZCE2mQy5DTg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
